### ISSUE TITLE
Page becomes unresponsive

### ISSUE THREAD

**Issue by ldrrp** [googleanalytics/ga-dev-tools#106]
https://ga-dev-tools.appspot.com/query-explorer/
This page becomes unresponsive when you authorize on an account that does not use google analytics. I switch between my work and personal gmail often

**Comment by philipwalton** [comment]
Thanks, this has been fixed. You should now get an alert if you attempt to use the Query Explorer and you don't have any Google Analytics accounts.

**Comment by philipwalton** [comment]
FWIW, what I do is make a separate [Google Chrome profile](https://support.google.com/chrome/answer/142059) for each of my Google accounts. I find that to be easier than switching, and it also allows me to have both mail accounts open at the same time.

**Comment by ldrrp** [comment]
Thanks for that, Also noted. Still getting use to chrome profiles
